# Generated by Django 3.1.1 on 2020-09-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room_name',
            field=models.CharField(default='old_room', max_length=20),
            preserve_default=False,
        ),
    ]
