# Generated by Django 3.1.1 on 2020-09-23 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('main_app', '0001_initial'), ('main_app', '0002_userfollowers_userprofile'), ('main_app', '0003_auto_20200917_1401'), ('main_app', '0004_auto_20200919_2033'), ('main_app', '0005_auto_20200923_0955')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=500)),
                ('airs_on', models.DateField()),
                ('ends_on', models.DateField(null=True)),
                ('added_on', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.userprofile')),
            ],
            options={
                'db_table': 'streams',
                'ordering': ['airs_on', 'author'],
            },
        ),
        migrations.CreateModel(
            name='UserFollowers',
            fields=[
                ('user_followers_id', models.AutoField(primary_key=True, serialize=False)),
                ('follower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.userprofile')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.userfollowers')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='')),
                ('country', models.CharField(default='Israel', max_length=100)),
                ('city', models.IntegerField(choices=[(1, 'Tel Aviv'), (2, 'HaMerkaz'), (3, 'HaDarom'), (4, 'HaTzafon')], default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('twitch_link', models.URLField(default='')),
                ('youtube_link', models.URLField(default='')),
            ],
        ),
    ]
