# Generated by Django 3.1.2 on 2020-11-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='genre',
            field=models.IntegerField(blank=True, choices=[(1, 'Education'), (2, 'Gaming'), (3, 'Music'), (4, 'Blog')], null=True),
        ),
    ]
