# Generated by Django 3.1.1 on 2020-09-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='description',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
