# Generated by Django 3.1.1 on 2020-09-17 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_userfollowers_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.userprofile'),
        ),
        migrations.AlterField(
            model_name='userfollowers',
            name='follower_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.userprofile'),
        ),
    ]
