# Generated by Django 3.1.1 on 2020-09-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200919_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='twitch_link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube_link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
